from backend.core.base import BaseArsenalModule
from backend.core.protocol import JobPacket, ResultPacket, Vulnerability, TaskTarget

# Lazy-init: import at call time to avoid blocking app startup (HIGH-49)
_cortex = None


def _get_cortex():
    global _cortex
    if _cortex is None:
        from backend.ai.cortex import get_cortex_engine
        _cortex = get_cortex_engine()
    return _cortex

class AuthBypassTester(BaseArsenalModule):
    def __init__(self):
        super().__init__()
        self.name = "Auth Bypass Tester"

    async def generate_payloads(self, packet: JobPacket) -> list[TaskTarget]:
        # 1. Try accessing without any headers (original)
        targets = []
        targets.append(TaskTarget(url=packet.target.url, method="GET", headers={}))
        
        # 2. HYBRID AI: Try AI-generated bypass headers
        ai_headers = await _get_cortex().generate_auth_bypass_headers(packet.target.url)
        for bypass_set in ai_headers:
             targets.append(TaskTarget(url=packet.target.url, method="GET", headers=bypass_set))
             
        return targets

    async def analyze_responses(self, interactions: list[tuple[TaskTarget, str]], packet: JobPacket) -> list[Vulnerability]:
        """Confirm auth bypass via differential analysis (Architecture §9, §17).

        A success keyword alone is insufficient. We require the bypass response
        to (a) contain authenticated-context markers AND (b) differ materially
        from a deny/baseline response, so >= 2 independent signals agree."""
        from backend.modules.evidence import differential

        vulnerabilities = []
        if not interactions:
            return vulnerabilities

        success_markers = ["admin", "dashboard", "welcome", "logout", "account", "profile"]

        baseline_target, baseline_text = interactions[0]
        baseline_text = baseline_text if isinstance(baseline_text, str) else ""

        for idx, (target, text) in enumerate(interactions):
            if not isinstance(text, str) or not text:
                continue
            low = text.lower()
            has_auth_markers = any(m in low for m in success_markers)
            if not has_auth_markers:
                continue

            # Differential vs baseline (index 0). For idx 0 itself, compare
            # against the smallest/most-restrictive sibling response.
            if idx == 0:
                others = [t for j, (_tg, t) in enumerate(interactions) if j != 0 and isinstance(t, str)]
                ref = min(others, key=len) if others else ""
                ev = differential(ref, text)
            else:
                ev = differential(baseline_text, text)

            # Require differential confirmation (>=2 signals) in addition to the
            # authenticated-context marker. Never confirm on substring alone.
            if not ev.verified:
                continue

            if idx == 0 and ("admin" in packet.target.url or "api/secure" in packet.target.url):
                vulnerabilities.append(Vulnerability(
                    name="Broken Access Control (No Auth)",
                    severity="CRITICAL",
                    description="Secure endpoint returned authenticated content without credentials.",
                    evidence=f"GET {packet.target.url} without headers succeeded. {ev.summary}",
                    remediation="Enforce authentication middleware on all secure routes."
                ))
            elif idx > 0:
                vulnerabilities.append(Vulnerability(
                    name="Auth Bypass (Header Injection)",
                    severity="HIGH",
                    description=f"Endpoint accessible with bypass headers: {list(target.headers.keys())}",
                    evidence=f"Headers: {target.headers}. {ev.summary}",
                    remediation="Validate auth tokens server-side, not via headers."
                ))
                break  # One confirmed bypass is enough
        return vulnerabilities
